# Clase 2 - Python Básico
## Diplomado en Argumentación y Narrativa Soportada en Análisis de Datos
### Politécnico Gran Colombiano - 2024
<img src= "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Logo_del_Polit%C3%A9cnico_Grancolombiano.svg/1200px-Logo_del_Polit%C3%A9cnico_Grancolombiano.svg.png" width=300>



# Funciones

Las funciones son fragmentos de código que agrupan un conjunto de instrucciones y devuelven un valor. Estas nos ayudan para separar el código en segmentos que nos facilitan encontrar errores y también nos permiten reciclar código.



    def nombre_de_la_funcion(parametro1, parametro2, ...):
        # Cuerpo de la función
        # Instrucciones que realizan la tarea
        return valor_a_retornar



In [135]:
def saludar():
    print("Hola")

saludar() 

Hola


In [136]:
def saludar(nombre):
    print("Hola,", nombre + "!")

saludar("Juan") 

Hola, Juan!


In [137]:
def aplicar_impuesto(subtotal,impuesto):
    return subtotal+subtotal*impuesto

aplicar_impuesto(100,0.16)

116.0

In [138]:
def aplicar_impuesto(subtotal,impuesto=0.16):
    return subtotal+subtotal*impuesto

In [139]:
aplicar_impuesto(100)

116.0

In [140]:
def aplicar_impuesto(subtotal=90,impuesto=0.16):
    return subtotal+subtotal*impuesto

In [141]:
aplicar_impuesto()

104.4

In [142]:
def perimetro_rect(a,b):
    return a*2+b*2

def area_rect(a,b):
    return a*b

def operaciones(a,b):
    return area_rect(a,b),perimetro_rect(a,b)

operaciones(2,5)

(10, 14)

In [143]:
def maximo(a, b):
    if a > b:
        return a
    else:
        return b

resultado = maximo(10, 5)
print(resultado)  

10


In [144]:
def es_par(numero):
    if numero % 2 == 0:
        return True
    else:
        return False

resultado = es_par(40)
print(resultado) 

True


# ¿Qué son los arrays?

En Python, los arrays son estructuras de datos que almacenan una colección de elementos del mismo tipo (homogéneos). Son similares a las listas, pero ofrecen ciertas ventajas en términos de eficiencia y operaciones numéricas, especialmente cuando se trabaja con grandes conjuntos de datos numéricos.

La biblioteca estándar de Python incluye un módulo llamado array que proporciona la funcionalidad de los arrays. Sin embargo, para realizar operaciones numéricas más avanzadas con arrays, se suele utilizar la biblioteca NumPy, que es la librería fundamental para la computación científica en Python.

## Propiedades de los arrays

    - Homogeneidad: Todos los elementos de un array deben ser del mismo tipo de dato (enteros, flotantes, caracteres, etc.).
    - Tamaño fijo: Una vez creado un array, su tamaño no puede modificarse directamente. Para cambiar su tamaño, es necesario crear un nuevo array.
    - Índices: Los elementos de un array se acceden mediante índices, que comienzan en 0.
    - Eficiencia: Los arrays suelen ser más eficientes que las listas para operaciones numéricas debido a su implementación optimizada.

In [145]:
import numpy as np

# Crear un array de enteros
enteros = np.array([1, 2, 3], dtype=np.int32)
print(enteros)

# Crear un array de flotantes
flotantes = np.array([1.5, 2.5, 3.5], dtype=np.float64)
print(flotantes)

[1 2 3]
[1.5 2.5 3.5]


In [146]:

# Crear dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Suma de arrays
suma = a + b
print(suma)

# Producto elemento a elemento
producto = a * b
print(producto)
# Media de un array
media = np.mean(a)
print(media)

[5 7 9]
[ 4 10 18]
2.0


In [147]:
# Crear un array de 0 a 9
arr = np.arange(10)
print(arr)
# Acceder al tercer elemento
print(arr[2])  # Output: 2

# Slicing para obtener los primeros 5 elementos
print(arr[:5])  

# Slicing para obtener elementos pares
print(arr[::2])  

[0 1 2 3 4 5 6 7 8 9]
2
[0 1 2 3 4]
[0 2 4 6 8]


## Broadcasting en NumPy

- El broadcasting es una característica poderosa que permite realizar operaciones entre arrays de diferentes formas. NumPy intenta "estirar" el array más pequeño para que coincida con las dimensiones del array más grande.

-Reglas del broadcasting:

    - Comparar las dimensiones de los arrays de derecha a izquierda.
    - Si una dimensión es 1, se "estira" para que coincida con la dimensión correspondiente del otro array.
    - Si las dimensiones no son compatibles, se produce un error.

In [148]:
## Broadcasting
# Crear un array de NumPy
numeros_np = np.array([1, 2, 3, 4, 5])

# Operaciones con arrays de NumPy
suma = numeros_np + 2  # Suma 2 a cada elemento
producto = numeros_np * 2  # Multiplica cada elemento por 2

print(suma)
print(producto)

[3 4 5 6 7]
[ 2  4  6  8 10]


### Matrices y Vectores Multidimensionales en Python: Un Enfoque con NumPy
   - Vectores: Son arreglos unidimensionales que representan una secuencia de elementos.
   - Matrices: Son arreglos bidimensionales que representan tablas de datos, con filas y columnas.
   - Tensores: Son generalizaciones de matrices a más de dos dimensiones.

<img src=https://miro.medium.com/v2/resize:fit:978/1*PxcT_3es1FG2EBsy9C3uxA.png>

<table>
<tr>
  <th> scalar, forma: <code>[]</code></th>
  <th> vector, forma: <code>[3]</code></th>
  <th> matriz, forma: <code>[3, 2]</code></th>
</tr>
<tr>
  <td>
   <img src="https://www.tensorflow.org/guide/images/tensor/scalar.png?hl=es-419" alt="A scalar, the number 4" />
  </td>

  <td>
   <img src=https://www.tensorflow.org/guide/images/tensor/vector.png?hl=es-419" alt="The line with 3 sections, each one containing a number."/>
  </td>
  <td>
   <img src="https://www.tensorflow.org/guide/images/tensor/matrix.png?hl=es-419" alt="A 3x2 grid, with each cell containing a number.">
  </td>
</tr>
</table>

In [149]:
x=np.array(4)
print('escalar:', x,x.shape)

escalar: 4 ()


In [150]:
import numpy as np

# Crear un vector fila
vector_fila = np.array([2, 3, 4])
print(vector_fila,vector_fila.shape)


[2 3 4] (3,)


In [151]:
# Crear un vector columna
vector_columna = np.array([ [2],
                            [3],
                            [4]])
print(vector_columna,vector_columna.shape)

[[2]
 [3]
 [4]] (3, 1)


| 1  | 2  | 3 |
|---|---|---|
| 4  | 5  | 6 |
| 7  | 8  | 9 |

In [152]:
# Crear una matriz 3x2
matriz = np.array([[1, 2],
                   [3,4],
                   [5,6]])
print(matriz)


[[1 2]
 [3 4]
 [5 6]]


In [153]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<table>
<tr>
  <th colspan=3>3-ejes tensor, forma: <code>[3, 2, 5]</code></th>
<tr>
<tr>
  <td>
   <img src="https://www.tensorflow.org/guide/images/tensor/3-axis_numpy.png?hl=es-419"/>
  </td>
  <td>
   <img src="https://www.tensorflow.org/guide/images/tensor/3-axis_front.png?hl=es-419"/>
  </td>

  <td>
   <img src="https://www.tensorflow.org/guide/images/tensor/3-axis_block.png?hl=es-419"/>
  </td>
</tr>

</table>

In [154]:
# Crear un tensor 3D de dimensiones 2x3x4
tensor = np.arange(30).reshape(3, 2, 5)
print(tensor,tensor.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


<table>
<tr>
  <th colspan=2>rango-4 tensor, forma: <code>[3, 2, 4, 5]</code></th>
</tr>
<tr>
  <td>
<img src="https://www.tensorflow.org/guide/images/tensor/shape.png?hl=es-419" alt="A tensor shape is like a vector.">
    <td>
<img src="https://www.tensorflow.org/guide/images/tensor/4-axis_block.png?hl=es-419" alt="A 4-axis tensor">
  </td>
  </tr>
</table>

In [155]:

# Crear un tensor 4D de dimensiones 3x2x4x5
tensor_4d = np.random.randint(0, 10, size=(3,2 , 4, 5))
print(tensor_4d,tensor_4d.shape)

[[[[9 2 7 2 0]
   [1 7 5 9 8]
   [1 4 8 0 1]
   [6 6 6 2 6]]

  [[0 5 7 1 1]
   [9 9 8 0 8]
   [5 5 0 4 4]
   [4 6 1 7 9]]]


 [[[4 3 6 8 9]
   [3 0 1 6 5]
   [2 8 0 2 8]
   [8 1 2 5 3]]

  [[8 6 9 3 7]
   [3 3 1 8 7]
   [9 0 9 8 2]
   [1 7 4 7 6]]]


 [[[7 4 6 3 3]
   [8 1 8 5 4]
   [7 9 0 8 8]
   [2 3 3 9 3]]

  [[6 5 2 5 1]
   [3 6 9 2 4]
   [7 8 3 2 2]
   [2 8 2 8 6]]]] (3, 2, 4, 5)


In [156]:
# Crear arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a.view())

[[1 2]
 [3 4]]


In [157]:
print(b.view())

[[5 6]]


In [158]:
# Concatenar verticalmente
c = np.concatenate((a, b), axis=0)
print(c)


[[1 2]
 [3 4]
 [5 6]]


In [159]:
# Concatenar horizontalmente
d = np.concatenate((a, b.T), axis=1)
print(d)  

[[1 2 5]
 [3 4 6]]


## División de Arrays

- La división de arrays puede referirse a:

    - División elemento a elemento: Se realiza con el operador /.
    - División entera: Se realiza con el operador //.
    - División matricial: Se realiza con la función np.linalg.inv.

In [160]:
# División elemento a elemento
a = np.array([10, 20, 30])
b = np.array([2, 5, 10])
c = a / b
print(c) 


[5. 4. 3.]


In [161]:
# División matricial (inversa)
A = np.array([[1, 2], [3, 4]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [162]:
##producto matricial
multi=np.matmul(A,inv_A)
print(multi)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [163]:
##producto matricial
multi=A@inv_A
print(multi)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [164]:
#El operador * en los numpy.ndarray realiza multiplicaciones elemento a elemento
print(A*A)

[[ 1  4]
 [ 9 16]]


### Transposición de Arrays

- La transposición intercambia filas y columnas de un array

In [165]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [166]:
###
a_transpose = a.T
print(a_transpose)

[[1 4]
 [2 5]
 [3 6]]


- Otras Operaciones Útiles:

    - Reshaping: Cambia la forma de un array sin modificar sus datos.
    - Stacking: Apila múltiples arrays a lo largo de un nuevo eje.
    - Splitting: Divide un array en múltiples subarrays.
    - tile:  repetir el arreglo varias veces a lo largo de los ejes

In [167]:
# Reshaping
a = np.arange(12).reshape(4, 3)
print(a,a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)


In [168]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apila verticalmente
stacked_vertical = np.vstack((a, b))
print(stacked_vertical)

[[1 2 3]
 [4 5 6]]


In [169]:
# Apila horizontalmente
stacked_horizontal = np.hstack((a, b))
print(stacked_horizontal)

[1 2 3 4 5 6]


In [170]:
c = np.array([7, 8, 9])
stacked_depth = np.dstack((a, b, c)) #a lo largo del tercer eje
print(stacked_depth)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [171]:
import numpy as np
x = np.arange(9)
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [172]:
#repetir el arrgle n veces
c = np.array([1,2,3,4])
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [173]:
#repetir el arrgle n veces
c = np.array([1,2,3,4])
np.tile(c,(1,4))

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

# CLASES:
#### Una clase es una plantilla que define cómo se creará un objeto. Los objetos son instancias de una clase. Las clases son una de las características más poderosas de Python y son fundamentales para la programación orientada a objetos (POO).

Crear una clase en Python se puede hacer un tan sólo dos líneas de código haciendo uso de la palabra class.
    
    class MiClase:
        pass

Podemos añadir algún atributo de clase. En este caso tenemos atributos generales que pertenecen a la clase

    class MiClase:
        atributo1 = "valor1"
        atributo2 = "valor2"

Toda clase tiene un constructor, que recibe unos parámetros de entrada cuando el objeto es creado. Creamos por lo tanto el constructor __init__.

    class MiClase:
        atributo1 = "valor1"
        atributo2 = "valor2"
        def __init__(self, argumento1):
            self.argumento1 = argumento1

A parte de atributos y el constructor, toda clase tiene un conjunto de funciones o métodos que realizan diferentes funcionalidades. Creamos la funcion1().

    class MiClase:
        atributo1 = "valor1"
        atributo2 = "valor2"
        def __init__(self, argumento1):
            self.argumento1 = argumento1
        def funcion1(self):
           print("Esta es la función 1")

A diferencia de la clase, un objeto define una clase particular, con unos atributos particulares para ese objeto. Es decir, el objeto es la instancia de la clase.

    mi_instancia_clase = MiClase("valor args")

Una vez tenemos el objeto mi_clase, podemos acceder a todo su contenido, tanto métodos como atributos de clase o de instancia. Simplemente hay que usar el objeto . y el método o atributo.

    mi_clase.atributo1
    mi_clase.atributo2
    mi_clase.argumento1
    mi_clase.funcion1()



In [180]:
class Perro:
    def __init__(self, nombre, raza):
        self.nombre = nombre
        self.raza = raza

    def ladrar(self):
        print(f"{self.nombre} está ladrando!")

    def jugar(self):
        print(f"{self.nombre} está jugando.")

    def comer(self,comida):
        print(f"{self.nombre} está comiendo {comida}.")

- class Perro:: Define una nueva clase llamada "Perro".
- __init__: Es un método especial llamado constructor. Se ejecuta automáticamente cuando se crea un nuevo objeto de la clase. Aquí se inicializan los atributos del objeto (nombre y raza).
- self: Hace referencia al objeto actual.
- ladrar y jugar: Son métodos que definen los comportamientos del objeto (ladrar y jugar).

In [181]:
mi_perro = Perro("Firulais", "Labrador")
otro_perro = Perro("Toby", "Pastor alemán")

In [182]:
mi_perro.raza

'Labrador'

In [186]:
otro_perro.raza

'Pastor alemán'

In [183]:
mi_perro.nombre

'Firulais'

In [184]:
mi_perro.ladrar()

Firulais está ladrando!


In [185]:
mi_perro.comer('concentrado')

Firulais está comiendo concentrado.


In [199]:
class CuentaBancaria:
    def __init__(self, titular, saldo_inicial=0):
        self.titular = titular
        self.saldo = saldo_inicial

    def depositar(self, cantidad):
        self.saldo += cantidad
        print(f"Se depositaron ${cantidad}. Saldo actual: ${self.saldo}")

    def retirar(self, cantidad):
        if cantidad <= self.saldo:
            self.saldo -= cantidad
            print(f"Se retiraron ${cantidad}. Saldo actual: ${self.saldo}")
        else:
            print("Fondos insuficientes.")

# Crear una cuenta bancaria
mi_cuenta = CuentaBancaria("Juan A", 10000)
otra_cuenta = CuentaBancaria("Pedro B", 10000)


In [192]:
mi_cuenta.titular

'Juan A'

In [193]:
mi_cuenta.saldo

10000

In [194]:
mi_cuenta.depositar(5000)

Se depositaron $5000. Saldo actual: $15000


In [195]:
mi_cuenta.saldo

15000

In [196]:
mi_cuenta.retirar(200)

Se retiraron $200. Saldo actual: $14800


In [197]:
mi_cuenta.saldo

14800

In [198]:
mi_cuenta.retirar(20000)

Fondos insuficientes.


In [200]:
otra_cuenta.titular

'Pedro B'

In [201]:
otra_cuenta.saldo

10000

Tarea: Herencia
Polimorfismo
Encapsulación
Métodos especiales (como __str__, __repr__)
Decoradores